version: '3.8'

services:
  # 1. Model Serving Anda
  app:
    image: noviardhana/diet-model:latest
    ports:
      - "5005:8080"
    networks:
      - monitoring_net

  # 2. Prometheus
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring_net

  # 3. Grafana
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Password default
    networks:
      - monitoring_net

networks:
  monitoring_net:
    driver: bridge